### ISSUE TITLE
template inline

### ISSUE THREAD

**Issue by huanz** [fouber/seajs-todo-demo#1]
template: __inline('/template/item.tmpl'),编译之后template是string了，无法直接执行~~~

**Comment by fouber** [comment]
@huanz 

我这里没有做前端模板的预编译，有两个方案：
1. 本地安装fis的前端模板预编译插件
2. 在前端引入模板引擎，对这个模板字符串进行运行时的编译

**Comment by huanz** [comment]
哦，刚试了一下你的那个fis-parser-utc插件，发现没有效果啊。在fis-conf.js里面的配置是：  fis.config.merge({
    modules: {
        parser: {
            tmpl: 'utc'
        }
    }
});

**Comment by fouber** [comment]
``` js
fis.config.set('modules.parser.tmpl', 'utc');
fis.config.get('roadmap.path').unshift({
    reg: '**.tmpl',
    release: false,
    isJsLike: true
});
```

**Comment by fouber** [comment]
@huanz

**Comment by huanz** [comment]
恩恩解决了。

ps：我觉得在spmx里面应该去掉模板预编译这个功能，因为加上这个预编译就得在fis-conf.js里面配置；但其实和你们一样，我只希望把模板文件内嵌进来而已，然后自己再去编译~
